// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as VendorMjs from "./vendor.mjs";

function jsx(prim0, prim1) {
  return VendorMjs.wrapper(prim0, prim1);
}

function jsxKeyed(prim0, prim1, prim2, prim3) {
  return VendorMjs.wrapper(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function jsxs(prim0, prim1) {
  return VendorMjs.wrapper(prim0, prim1);
}

function jsxsKeyed(prim0, prim1, prim2, prim3) {
  return VendorMjs.wrapper(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

var jsxFragment = VendorMjs.Fragment;

function jsx$1(prim0, prim1) {
  return VendorMjs.wrapper(prim0, prim1);
}

function div(prim0, prim1) {
  return VendorMjs.wrapper(prim0, prim1);
}

function jsxKeyed$1(prim0, prim1, prim2, prim3) {
  return VendorMjs.wrapper(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

function jsxs$1(prim0, prim1) {
  return VendorMjs.wrapper(prim0, prim1);
}

function jsxsKeyed$1(prim0, prim1, prim2, prim3) {
  return VendorMjs.wrapper(prim0, prim1, prim2 !== undefined ? Caml_option.valFromOption(prim2) : undefined);
}

var Elements = {
  jsx: jsx$1,
  div: div,
  jsxKeyed: jsxKeyed$1,
  jsxs: jsxs$1,
  jsxsKeyed: jsxsKeyed$1
};

export {
  jsx ,
  jsxKeyed ,
  jsxs ,
  jsxsKeyed ,
  jsxFragment ,
  Elements ,
}
/* jsxFragment Not a pure module */
